IF EXISTS (SELECT*FROM sys.databases WHERE NAME='dienthoai') 
DROP DATABASE dienthoai
CREATE DATABASE dienthoai
GO

CREATE TABLE CUSTOMER(
    CUSID INT PRIMARY KEY NOT NULL,
    NAME VARCHAR(30),
    ID VARCHAR(30),
    ADDRESS VARCHAR(30)
)

CREATE TABLE PHONENUMBER(
    PHONEID INT PRIMARY KEY NOT NULL,
    CUSID INT FOREIGN KEY(CUSID) REFERENCES CUSTOMER(CUSID),
    TEL VARCHAR (30),
    STATUS VARCHAR (30),
    REGISTERDATE DATE

)

CREATE TABLE PHONEDETAILS(
    PDETAILID INT,
    PHONEID INT FOREIGN KEY (PHONEID) REFERENCES PHONENUMBER(PHONEID),
    NAME VARCHAR (30)

)

INSERT INTO CUSTOMER(CUSID,NAME,ID,ADDRESS) VALUES(123,'NGUYENNGUYETNGA','123456789','HANOI')
INSERT INTO CUSTOMER(CUSID,NAME,ID,ADDRESS) VALUES(789,'TUAN','90','VINHPHUC')

INSERT INTO PHONENUMBER(PHONEID,CUSID,TEL,STATUS,REGISTERDATE) VALUES(234,123,'0123456789','OK','3-7-2022')
INSERT INTO PHONENUMBER(PHONEID,CUSID,TEL,STATUS,REGISTERDATE) VALUES(788,789,'0973201445','OK','3-8-2022')

INSERT INTO PHONEDETAILS(PDETAILID,PHONEID,NAME) VALUES(456,234,'TRASAU')
INSERT INTO PHONEDETAILS(PDETAILID,PHONEID,NAME) VALUES(478,788,'TRASAU')

SELECT * FROM CUSTOMER
SELECT * FROM PHONENUMBER

SELECT * FROM CUSTOMER
WHERE  ID='123456789'

SELECT * FROM PHONENUMBER
WHERE  TEL='0123456789'

SELECT * FROM PHONENUMBER
WHERE  CUSID=123

SELECT *FROM PHONENUMBER
WHERE REGISTERDATE='3-7-2022'

SELECT * FROM CUSTOMER
WHERE ADDRESS='HANOI'

SELECT COUNT(DISTINCT NAME ) FROM CUSTOMER

SELECT COUNT(DISTINCT TEL ) FROM PHONENUMBER

SELECT COUNT(DISTINCT TEL ) FROM PHONENUMBER WHERE REGISTERDATE='3-7-2022'

SELECT * FROM CUSTOMER,PHONENUMBER   --KHOS

ALTER TABLE PHONENUMBER
ALTER COLUMN REGISTERDATE DATE NOT NULL

ALTER TABLE PHONENUMBER
ADD CONSTRAINT CNT CHECK(REGISTERDATE <= GETDATE() )



ALTER TABLE PHONENUMBER
ADD CONSTRAINT MVT CHECK(TEL LIKE '0%')

ALTER TABLE PHONENUMBER
ADD SODIEM INT 

 



