IF EXISTS (SELECT*FROM sys.databases WHERE NAME='sanpham') 
DROP DATABASE sanpham
CREATE DATABASE sanpham
GO

CREATE TABLE DSSANPHAMTHEOHANG(
    IDHANG INT ,
    TENHANG VARCHAR(100) PRIMARY KEY NOT NULL,
    DIACHI VARCHAR(100),
    SDT VARCHAR (100)
)

CREATE TABLE DSSANPHAM(
    IDSANPHAM INT,
    TENSANPHAM VARCHAR(100),
    MOTASANPHAM VARCHAR(100),
    DONVI VARCHAR(100),
    GIA MONEY,
    SOLUONGHIENCO INT,
    HANGSANXUAT VARCHAR(100) FOREIGN KEY(HANGSANXUAT) REFERENCES DSSANPHAMTHEOHANG(TENHANG)



)

INSERT INTO DSSANPHAMTHEOHANG(IDHANG,TENHANG,DIACHI,SDT) VALUES(123,'APPLE','USA','097320113')
INSERT INTO DSSANPHAMTHEOHANG(IDHANG,TENHANG,DIACHI,SDT) VALUES(456,'SAMSUNG','KOREA','02803118')
INSERT INTO DSSANPHAM VALUES(789,'MAYDIENTHOAI','MAYMOI','CHIEC','1000','15','APPLE')
INSERT INTO DSSANPHAM VALUES(246,'MAYHUTBUI','MAYMOI','CHIEC','1000','10','SAMSUNG')
INSERT INTO DSSANPHAM VALUES(389,'NOICOM','MAYMOI','CHIEC','500','12','SAMSUNG')
INSERT INTO DSSANPHAM VALUES(019,'QUAT','MAYMOI','CHIEC','700','10','APPLE')



SELECT* FROM DSSANPHAMTHEOHANG
SELECT* FROM DSSANPHAM

SELECT TENHANG FROM DSSANPHAMTHEOHANG
SELECT TENSANPHAM FROM DSSANPHAM

SELECT*FROM DSSANPHAMTHEOHANG ORDER BY TENHANG DESC
SELECT*FROM DSSANPHAM ORDER BY GIA DESC

SELECT * FROM DSSANPHAMTHEOHANG
WHERE  TENHANG='APPLE'

SELECT  SOLUONGHIENCO  FROM DSSANPHAM
WHERE SOLUONGHIENCO<11

SELECT HANGSANXUAT FROM DSSANPHAM
WHERE HANGSANXUAT='APPLE'

SELECT * FROM DSSANPHAM
WHERE  HANGSANXUAT='APPLE'

SELECT *  FROM DSSANPHAM
WHERE SOLUONGHIENCO<11

SELECT COUNT(DISTINCT IDHANG ) FROM DSSANPHAMTHEOHANG

SELECT COUNT(DISTINCT HANGSANXUAT ) FROM DSSANPHAM



SELECT COUNT(DISTINCT TENSANPHAM ) FROM DSSANPHAM

SELECT COUNT(DISTINCT TENSANPHAM)FROM DSSANPHAM WHERE HANGSANXUAT= 'APPLE'

SELECT COUNT(DISTINCT TENSANPHAM)FROM DSSANPHAM WHERE HANGSANXUAT= 'SAMSUNG'

SELECT SUM( SOLUONGHIENCO ) FROM DSSANPHAM WHERE  SOLUONGHIENCO>0

ALTER TABLE DSSANPHAM
ADD CONSTRAINT MOP CHECK( GIA >0)

ALTER TABLE DSSANPHAMTHEOHANG
ADD CONSTRAINT MLER CHECK(SDT LIKE '0%')

CREATE INDEX idx_pname
ON DSSANPHAM (TENSANPHAM, MOTASANPHAM);

CREATE VIEW [View_SanPham] AS
SELECT TENSANPHAM, IDSANPHAM, GIA
FROM DSSANPHAM

SELECT * FROM [View_SanPham]

CREATE VIEW [View_SanPham_Hang] AS (
SELECT DSSANPHAM.IDSANPHAM ,DSSANPHAM.TENSANPHAM,DSSANPHAMTHEOHANG.TENHANG
FROM DSSANPHAM,DSSANPHAMTHEOHANG
WHERE DSSANPHAMTHEOHANG.TENHANG=DSSANPHAM.HANGSANXUAT
)


CREATE VIEW MAB AS 
SELECT IDSANPHAM,TENSANPHAM,TENHANG
FROM DSSANPHAM C INNER JOIN DSSANPHAMTHEOHANG B ON B.TENHANG = C.HANGSANXUAT

sp_helptext MAB

CREATE VIEW MTL WITH ENCRYPTION AS
SELECT IDSANPHAM,TENSANPHAM,TENHANG
FROM DSSANPHAM C INNER JOIN DSSANPHAMTHEOHANG B ON B.TENHANG = C.HANGSANXUAT

sp_helptext MTL

SELECT * FROM [View_SanPham_Hang]


 












