IF EXISTS (SELECT*FROM sys.databases WHERE NAME='QUANLYSANPHAM') 
DROP DATABASE QUANLYSANPHAM
CREATE DATABASE QUANLYSANPHAM
GO

CREATE TABLE NHANVIEN(
 NAMENV VARCHAR(50),
 IDNHANVIEN INT PRIMARY KEY NOT NULL 

)

CREATE TABLE LOAISANPHAM(
 MALOAISANPHAM INT PRIMARY KEY NOT NULL,
 TENLOAISANPHAM VARCHAR(50)
)

 CREATE TABLE SANPHAM(
  MASANPHAM INT, 
  IDNHANVIEN INT FOREIGN KEY (IDNHANVIEN) REFERENCES NHANVIEN (IDNHANVIEN),
  MALOAISANPHAM INT FOREIGN KEY (MALOAISANPHAM) REFERENCES LOAISANPHAM (MALOAISANPHAM),
  NGAYSX DATE,
  TENSANPHAM VARCHAR (50)

)

INSERT INTO NHANVIEN(NAMENV,IDNHANVIEN) VALUES('MINH',123)
INSERT INTO NHANVIEN(NAMENV,IDNHANVIEN) VALUES('QUANG',113)
INSERT INTO NHANVIEN(NAMENV,IDNHANVIEN) VALUES('NGUYENVANAN',987688)




INSERT INTO LOAISANPHAM(MALOAISANPHAM,TENLOAISANPHAM) VALUES(456,'DIENTHOAI')
INSERT INTO LOAISANPHAM(MALOAISANPHAM,TENLOAISANPHAM) VALUES(455,'NOICOM')
INSERT INTO LOAISANPHAM(MALOAISANPHAM,TENLOAISANPHAM) VALUES(37,'MAYTINHSACHTAYZ37')



INSERT INTO SANPHAM(MASANPHAM,IDNHANVIEN,MALOAISANPHAM,NGAYSX,TENSANPHAM) VALUES(789,123,456,'3-7-2022','DIENTHOAIIPHONE')
INSERT INTO SANPHAM(MASANPHAM,IDNHANVIEN,MALOAISANPHAM,NGAYSX,TENSANPHAM) VALUES(778,113,455,'3-8-2022','NOICOMSAMSUNG')
INSERT INTO SANPHAM(MASANPHAM,IDNHANVIEN,MALOAISANPHAM,NGAYSX,TENSANPHAM) VALUES(37111111,987688,37,'12-12-2009','MAYTINHSACHTAY')


SELECT TENLOAISANPHAM FROM LOAISANPHAM

SELECT TENSANPHAM FROM SANPHAM

SELECT NAMENV FROM NHANVIEN

SELECT*FROM LOAISANPHAM ORDER BY TENLOAISANPHAM ASC

SELECT*FROM NHANVIEN ORDER BY NAMENV ASC

SELECT * FROM LOAISANPHAM
WHERE  MALOAISANPHAM=37

SELECT SANPHAM.TENSANPHAM
FROM NHANVIEN , SANPHAM
WHERE NHANVIEN.NAMENV = 'NGUYENVANAN' AND NHANVIEN.IDNHANVIEN = SANPHAM.IDNHANVIEN
ORDER BY SANPHAM.TENSANPHAM DESC

SELECT  LOAISANPHAM.TENLOAISANPHAM ,COUNT (SANPHAM.MALOAISANPHAM)  
FROM SANPHAM, LOAISANPHAM 
WHERE SANPHAM.MALOAISANPHAM = LOAISANPHAM.MALOAISANPHAM
GROUP BY LOAISANPHAM.TENLOAISANPHAM

SELECT LOAISANPHAM.MALOAISANPHAM,LOAISANPHAM.TENLOAISANPHAM, SANPHAM.MASANPHAM,SANPHAM.IDNHANVIEN,SANPHAM.MALOAISANPHAM,SANPHAM.NGAYSX,SANPHAM.TENSANPHAM
    FROM LOAISANPHAM 
    INNER JOIN SANPHAM ON LOAISANPHAM.MALOAISANPHAM=SANPHAM.MALOAISANPHAM


SELECT LOAISANPHAM.MALOAISANPHAM,LOAISANPHAM.TENLOAISANPHAM, SANPHAM.MASANPHAM,SANPHAM.IDNHANVIEN,SANPHAM.MALOAISANPHAM,SANPHAM.NGAYSX,SANPHAM.TENSANPHAM,NHANVIEN.NAMENV,NHANVIEN.IDNHANVIEN
FROM LOAISANPHAM 
INNER JOIN SANPHAM ON LOAISANPHAM.MALOAISANPHAM=SANPHAM.MALOAISANPHAM
INNER JOIN NHANVIEN ON NHANVIEN.IDNHANVIEN=SANPHAM.IDNHANVIEN


ALTER TABLE SANPHAM
ADD CONSTRAINT MCC CHECK(NGAYSX <= GETDATE() )

ALTER TABLE SANPHAM
ADD PHIENBAN VARCHAR(50) 

SELECT * FROM SANPHAM





